version: '2'
services:
        backend:
                build: backend
                volumes:
                 - /usr/src/app/static
                links:
                 - bdd
                restart: always
        frontend:
                build: frontend
                ports:
                 - "80:80"
                volumes_from:
                 - backend:ro
                links:
                 - backend
                restart: always
        bdd:
                image: mysql:5.7
                environment:
                 - MYSQL_ROOT_PASSWORD=he8dau6V
                 - MYSQL_USER=django
                 - MYSQL_PASSWORD=ohTh3qui
                 - MYSQL_DATABASE=comif 
                volumes:
                 - ./bdd:/var/lib/mysql
                restart: always
